fail_fast: false
default_language_version:
  python: python3.11
repos:
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [
      "--remove-all-unused-imports",
      "--ignore-init-module-imports",
      "--in-place",
      "--recursive",
    ]

- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black"]
    additional_dependencies: ['.[pyproject]']

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    additional_dependencies: ['click==8.0.4']
